Samael gray texture updates
CombatExtended-Continued/CombatExtendedGuns pull request #119
Opened 2024-10-08 10:39 UTC by SamaelGray

## Changes

- Updated the RPD's texture, some more will follow.
- Centered textures vertically to not need Y axis offsetting.

2024-10-08 11:40 UTC, Safairette requested changes, later dismissed
Some issues with the RPD retexture that should be fixed before merging.

2024-10-08 11:40 UTC, Safairette commented on Textures/Things/Weapons/RPD.png
Relaying the same thing I said on discord: the compression issues on the stock, the lack of visible shape on the handguard and the more detailed barrel getting fuzzy in game makes this retexture a downgrade compared to the previous.

2024-10-08 12:42 UTC, Safairette commented on Textures/Things/Weapons/RPD.png
Compression artifacts and the blurring of details on the barrel are still there

2024-10-08 13:10 UTC, SamaelGray commented on Textures/Things/Weapons/RPD.png
Keep things civil on github. The barrel section is the same across most other weapons in CE and the compression is not something I can wave a magic wand over and fix so unless you provide a solution, the conversation is solved.

2024-10-08 15:13 UTC, Safairette commented on Textures/Things/Weapons/RPD.png
The texture you're adding has several visual issues that weren't present in the previous one, so I'm requesting you fix them. And if you refuse to do so, at least provide the source files so that others can do so.

2024-12-07 23:07 UTC, N7Huntsman approved these changes

2024-12-07 23:07 UTC, merged